name: RSpec tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0', head]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Execute the tests
      run: bundle exec rspec
